// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBCORELP2021.Models;

namespace WEBCORELP2021.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210912021606_Anotacoes_v1")]
    partial class Anotacoes_v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WEBCORELP2021.Models.Dominio.Consulta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("medicoid")
                        .HasColumnType("int");

                    b.Property<int?>("pacienteid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("medicoid");

                    b.HasIndex("pacienteid");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("WEBCORELP2021.Models.Dominio.Medico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numero")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("WEBCORELP2021.Models.Dominio.Paciente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idade")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("WEBCORELP2021.Models.Dominio.PlanoDeSaude", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("pacienteid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("pacienteid");

                    b.ToTable("PlanosDeSaude");
                });

            modelBuilder.Entity("WEBCORELP2021.Models.Dominio.Consulta", b =>
                {
                    b.HasOne("WEBCORELP2021.Models.Dominio.Medico", "medico")
                        .WithMany("consultas")
                        .HasForeignKey("medicoid");

                    b.HasOne("WEBCORELP2021.Models.Dominio.Paciente", "paciente")
                        .WithMany("consultas")
                        .HasForeignKey("pacienteid");

                    b.Navigation("medico");

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("WEBCORELP2021.Models.Dominio.PlanoDeSaude", b =>
                {
                    b.HasOne("WEBCORELP2021.Models.Dominio.Paciente", "paciente")
                        .WithMany("planoDeSaude")
                        .HasForeignKey("pacienteid");

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("WEBCORELP2021.Models.Dominio.Medico", b =>
                {
                    b.Navigation("consultas");
                });

            modelBuilder.Entity("WEBCORELP2021.Models.Dominio.Paciente", b =>
                {
                    b.Navigation("consultas");

                    b.Navigation("planoDeSaude");
                });
#pragma warning restore 612, 618
        }
    }
}
